### ISSUE TITLE
How to SSL kill switch on selected domains only?

### ISSUE THREAD

**Issue by radj** [iSECPartners/ios-ssl-kill-switch#11]
I tried using SSLGetPeerDomainName() on the SSLContextRef objects so I can check the domain for the current session but it doesn't always return a value. Are there other ways to do this?

**Comment by nabla-c0d3** [comment]
I am not familiar with SSLGetPeerDomainName() but doing this per domain seems complex. Why not do it on a per-App basis ?

**Comment by radj** [comment]
Thanks for getting back quickly. It was a rather specific requirement. An app makes calls to different domains and we're trying to intercept SSL traffic on some, but let normal validation happen on the others.

**Comment by nabla-c0d3** [comment]
You could selectively hijack/intercept connections by using your own DNS server (such as https://github.com/iSECPartners/dnsRedir) but the validation would still be disabled for all connections. 

If you really need to leave the validation untouched for specific domains (a strange requirement), you may have to hook a higher level API. 
If the App is using NSURLConnection for the calls, you could easily modify the old version of ssl-kill-switch which was hooking NSURLConnection only: https://github.com/iSECPartners/ios-ssl-kill-switch/blob/delegate-hook/Tweak.xm
By inspecting the NSURLRequest in the constructor, you can make a decision on whether SSL validation should be disabled or not.

**Comment by radj** [comment]
Yeah, it is strange but it is what it is ;)

Thank you! This will get me started!

**Comment by radj** [comment]
@nabla-c0d3 Just curious, why the switch from NSURLConnection hooks to the SecTransport? Is SecTransport the underlying mechanism for HTTPS handling in NSURLConnection?

**Comment by nabla-c0d3** [comment]
Yes it is. Anything SSL/HTTPS in the Apple frameworks is built on top of Secure Transport which is why ssl-kill-switch works for everything.

**Comment by radj** [comment]
I see. Thank you for confirming.
