### ISSUE TITLE
AppStore user login not working

### ISSUE THREAD

**Issue by isayeter** [iSECPartners/ios-ssl-kill-switch#14]
Hello,

When I open AppStore in my ipad, everything works fine, but when I try to download an app ipad asks my appleid, when I enter it and press OK, it says "couldn't connect to appstore"

**Comment by nabla-c0d3** [comment]
Try this: https://nabla-c0d3.github.io/blog/2013/08/20/intercepting-the-app-stores-traffic-on-ios/
