### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by Noagi6493** [iSECPartners/ios-ssl-kill-switch#26]
Issue closed, reinstalled it now it works

**Comment by Noagi6493** [comment]
For thoose of you affected by this, here is how to remove

1. boot your device into safe mode by force resetting by holding power button and home button

2. when the device reboots hold the volume up and powr button and let go of the power button when you see the apple logo but keep holding the volume up button while your device boots up

3. your tweaks will be disabled but your touchscreen will work, get a SSH Manager (i reccomend WinSCP)

4. ssh intio your device (if your on WinSCP open a terminal) and preform this command

dpkg -r com.isecpartners.nabla.sslkillswitch

5. reboot your device and your touchscreen works and this software is removed

reinstall it and if it still doesnt work idk whats causing it

**Comment by iamvinny** [comment]
lmao

**Comment by Noagi6493** [comment]
what?
