### ISSUE TITLE
Can't work with AppStore.app in iOS 6.x

### ISSUE THREAD

**Issue by sunlei** [iSECPartners/ios-ssl-kill-switch#6]
Can't work with AppStore.app in iOS 6.x.

AppStore.app said "Cannot connect to iTunes Store".

**Comment by nabla-c0d3** [comment]
Thanks for the feedback. I'll look into it when I have time; the AppStore is probably doing something special.

**Comment by jimzhao2012** [comment]
yep，i test already, Path use ssl pinning, it works well for Path after i set and restart springboard. but can't work for 6.x AppStore.
hope it will be support for AppStore asap, thanks.

**Comment by nabla-c0d3** [comment]
Using the latest version, you should be able to proxy the App Store. Instructions are available here:
http://nabla-c0d3.github.io/blog/2013/08/20/intercepting-the-app-stores-traffic-on-ios/
