### ISSUE TITLE
ios 7

### ISSUE THREAD

**Issue by evolut1on** [iSECPartners/ios-ssl-kill-switch#8]
Hello sir,

First step, after installing the jailbreak for iOS 7.0.4, was to install killssl. Sadly, it seems that the button won't appear. Do you plan to resolve this issue?

Cheers!

**Comment by nabla-c0d3** [comment]
Hi,
Support for iOS 7 will be added soon.

**Comment by evolut1on** [comment]
it seems that mobile substrate&preferenceloader has been updated and now the killssl switch appears in the settings menu, but still it doesn;t work

**Comment by nabla-c0d3** [comment]
Try the package I just released at https://github.com/iSECPartners/ios-ssl-kill-switch/releases 
It worked fine on an iphone 5s.
